calix/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('main.urls')),
    path('', include('right.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# 01732168213

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home-main'),

    path('advisers/', views.advisers, name='advisers'),
    path('advisers/<int:id>', views.adviser, name='adviser'),

    path('directors/', views.directors, name='directors'),
    path('directors/<int:id>', views.director, name="director"),

    path('committee/', views.committee, name='committee'),

    path('teachers/', views.teachers, name='teachers'),
    path('teachers/<int:id>', views.teacher, name='teacher'),

    path('lib/', views.lib, name='lib'),
    path('annualreport/', views.annualreport, name='annualreport'),

    path('expectation/', views.expectation, name='expectation'),
    path('expectation/add', views.add_expectation, name='add-expectation'),



    path('socialworks/', views.socialworks, name='socialworks'),

    path('about_us/', views.about_us, name='about_us'),
    path('started/', views.started, name='started'),
    path('kids/', views.kids, name='kids'),
    path('contact/', views.contact, name='contact'),
]

templates/pages/about_us.html
{% extends 'master.html' %} 
{% load static %} 

{% block head %}
<link rel="stylesheet" href="{% static 'css/teachers.css' %}" />
{% endblock head %} 


{% block title %}
প্রতিষ্ঠানের তথ্য - ক্যালিক্স স্কুল এন্ড কলেজ
{% endblock title %}

{% block poster %} 
{% include 'poster.html' %}
{% endblock poster %}

{% block main %}

<div class="teachers__title red-green-center ">
  <h1>
    <p>
      প্রতিষ্ঠানের তথ্য
    </p>
  </h1>
</div>

{% endblock main %}

templates/pages/add_expectation.html
{% extends 'master.html' %} 
{% load static %} 

{% block head %}
<link rel="stylesheet" href="{% static 'css/teachers.css' %}" />
<link rel="stylesheet" href="{% static 'css/expectation.css' %}" />



{% endblock head %} 


{% block title %}
প্রত্যাশা - ক্যালিক্স স্কুল এন্ড কলেজ
{% endblock title %}

{% block poster %} 
{% include 'poster.html' %}
{% endblock poster %}

{% block main %}
<main class="main-add_expectation" >
 

  <div class="visitor-input">

    <div class="input-wrap">
      <form class="input__form" id="form" action="#" method="POST">

        {{form.as_p}}
        {{form.media}}
      
      </form>
    </div>

  </div>
</main>
{% endblock main %}

templates/pages/advisers.html
{% extends 'master.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/advisers.css' %}">

{% endblock head %}

{% block title %}
সম্মানিত উপদেষ্টা মণ্ডলী - ক্যালিক্স স্কুল এন্ড কলেজ 
{% endblock title %}

{% block poster %}
{% include 'poster.html' %}
{% endblock poster %}

{% block main %}
<main class="advisers__main">

      <div class="advisers__title">
        <h1><p>সম্মানিত উপদেষ্টা মণ্ডলী</p></h1>
      </div>

      <div class="advisers__grid grid">
        {% for item in advisers %}
          <div class="card" id="card" data-href="{{item.id}}" >
              <div class="card__contenido">
                <h3 class="card__title">{{item.position}}</h3>
                <h4 class="card__subtitle">
                {{item.full_name}}  
                </h4>
                <div class="divider">&nbsp;</div>
                <div class="card__text">
                {{item.short_description | safe}}
                </div>
                <a href=" {{item.id}} " class="card__readbtn "> &nbsp; </a>
              </div>
          </div>
      {% endfor %}
    </div>
</main>
{% endblock main %}

{% block js %}
<script>

const card = document.getElementsByClassName("card");

for (let i = 0; i < card.length; i++) {
  const e = card[i];

  console.log(e);

  e.style.cursor = "pointer";
  e.addEventListener("click", (_) => {
    window.location.assign(e.dataset.href);
  });
}

</script>

{% endblock js %}

templates/pages/annualreport.html
{% extends 'master.html' %} 
{% load static %} 

{% block head %}
<link rel="stylesheet" href="{% static 'css/teachers.css' %}" />
<link rel="stylesheet" href="{% static 'css/lib.css' %}" />

<style>
  .annualreport__title h1 p{
    padding: .7rem 3.0rem;
  }
</style>
{% endblock head %} 


{% block title %}
বার্ষিক প্রতিবেদন - ক্যালিক্স স্কুল এন্ড কলেজ
{% endblock title %}

{% block poster %} 
{% include 'poster.html' %}
{% endblock poster %}

{% block main %}

<main class="main-reports">

  <div class="annualreport__title red-green-center ">
  <h1>
    <p>
      বার্ষিক প্রতিবেদন
    </p>
  </h1>
</div>


  {% for item in reports %}
   <div class="lib__title red-green-center">
      <h1>
      <p>
       {{item.short_name}}
      </p>
    </h1>
  </div>

      <h1 class="lib__title-promary" >{{item.title_of_post}}</h1>
      <div class="adviser__desc">

        {{item.description | safe}}
      </div>

      </div>
        {% endfor %}


</main>

{% endblock main %}

templates/pages/committee.html
{% extends 'master.html' %} 
{% load static %} 

{% block head %}

<link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">

<style>
  .table__container{
    font-family: Arial, Helvetica, sans-serif;
    color: black;
    background-color: #009951;

    max-width: 100.0rem;
    padding: 3.0rem;
    
    margin-top: .0rem;
    margin-right: auto;
    margin-bottom: 5.0rem;
    margin-left: auto;

    text-align: center;
  }
  #myTable{
    padding-top: 1.5rem;
  }
  thead{
    background-color: red;
    color: #fff;
     margin-top: 1.0rem;
  }
  .next{
    top: auto;
    position: initial;
  }

</style>

{% endblock head %} 


{% block title %}
কমিটির সম্মানিত সদস্যবৃন্দ  - ক্যালিক্স স্কুল এন্ড কলেজ
{% endblock title %}

{% block poster %} 
{% include 'poster.html' %} 
{% endblock poster %}


{% block main %}
<main>

<div class="committee__title red-green-center">
  <h1>
    <p>
      কমিটির সম্মানিত সদস্যবৃন্দ
    </p>
  </h1>
</div>

<div class="table__container">
  <table id="myTable" class="display">
      <thead>
          <tr>
              <th>নাম</th>
              <th>পদবি</th>
              <th>মোবাইল নাম্বার</th>
              <th>ই-মেইল</th>
              <th>ঠিকানা</th>
          </tr>
      </thead>
      <tbody>

        {% for member in members %}
            <tr>
              <td>{{member.full_name}}</td>
              <td>{{member.position}}</td>
              <td>{{member.phone}}</td>
              <td>{{member.email}}</td>
              <td>{{member.location}}</td>
            </tr>
        {% endfor %}

      </tbody>
  </table>
</div>
</main>

{% endblock main %}

{% block js %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
    
<script>
$(document).ready( function () {
    $('#myTable').DataTable();
});

    
</script>

{% endblock js %}


  



 
  

templates/pages/contact.html
{% extends 'master.html' %} 
{% load static %} 

{% block head %}
<link rel="stylesheet" href="{% static 'css/teachers.css' %}" />
{% endblock head %} 


{% block title %}
যোগাযোগ - ক্যালিক্স স্কুল এন্ড কলেজ
{% endblock title %}

{% block poster %} 
{% include 'poster.html' %}
{% endblock poster %}

{% block main %}

<div class="teachers__title red-green-center ">
  <h1>
    <p>
      যোগাযোগ
    </p>
  </h1>
</div>

{% endblock main %}

templates/pages/director.html
{% extends 'master.html' %} 

{% load static %} 

{% block head %}
<link rel="stylesheet" href="{% static 'css/director.css' %}" />
{% endblock head %} 

{% block title %} 
{{director.full_name}} - ক্যালিক্স স্কুল এন্ড কলেজ
{% endblock title %}

{% block poster %} 
{% include 'poster.html' %} 
{% endblock poster %} 

{% block main %}

<main class="director__main">

<div class="director__title red-green-center">
  <h1>
    <p>{{director.position}}</p>
  </h1>
</div>


  <section class="director">
        <div class="director__img">
              <img
                src="https://images.unsplash.com/photo-1572449043416-55f4685c9bb7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80"
                alt="{{director.full_name}} এর ছবি"
              />
        </div>
        
        <hr>

        <h1>{{director.full_name}}</h1>
        <div class="director__description">
          {{director.description| safe}}
        </div>
        <hr>
        <a class="link link-btn" target="_blank" href="{{director.facebook}}">
          <svg aria-hidden="true" focusable="false" data-prefix="fab" data-icon="facebook-square" class="svg-facebook" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M400 32H48A48 48 0 0 0 0 80v352a48 48 0 0 0 48 48h137.25V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.27c-30.81 0-40.42 19.12-40.42 38.73V256h68.78l-11 71.69h-57.78V480H400a48 48 0 0 0 48-48V80a48 48 0 0 0-48-48z"></path>
          </svg>
        </a>
  </section> 

  </div>
</main>

{% endblock main %}

templates/pages/directors.html
{% extends 'master.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/advisers.css' %}" />
<link rel="stylesheet" href="{% static 'css/card.css' %}" />

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

{% endblock head %} 

{% block title %} 
পরিচালকবৃন্দ - ক্যালিক্স স্কুল এন্ড কলেজ
{% endblock title %}

{% block poster %} 
{% include 'poster.html' %} 
{% endblock poster %} 

{% block main %}
<div class="directors__title red-green-center">
  <h1>
    <p>পরিচালকবৃন্দ</p>
  </h1>
</div>
<main class="directors-main">




   
      {% comment %} <div class="card" data-href="{{director.pk}}">
        <div class="card__contenido">
            <h3 class="card__title">{{director.full_name}}</h3>
            <h4 class="card__subtitle">
              {{director.position}}
            </h4>
            <div class="divider">&nbsp;</div>
            <p class="card__text">
              {{director.short_description |safe}}
            </p>
          </div>
      </div> {% endcomment %}


      





      <div class="directors-container">
         {% for director in directors %}
        <div class="director">

          {% comment %} start flip orginal {% endcomment %}

            <div class="container">
              <div class="product">
                <div class="product-inner" id="productBox">
                  
                  <div class="product-front">
                    <div class="product-top">
                      <h1>{{director.full_name}}</h1>
                    </div>
                    <div class="product-bottom">
                      <p>Nike running shoes</p>
                      <h2>{{director.position}}</h2>
                      <h1><span>$</span>120</h1>
                      <a href="{{director.phone}}"> {{director.phone}} </a>
                      <div class="color-select">
                        <div class="select-item">Back</div>
                      </div>
                    </div>
                  </div>
                  {% comment %} end of product front {% endcomment %}
                  
                  <div class="product-back">
                    <div class="product-top product-top2">
                      <h1>{{director.position}}</h1>
                    </div>
                    <div class="product-bottom">
                      <p>Students helping the poor</p>
                      <h2>Air Zoom Winflo 6</h2>
                      <h1><span>&nbsp;</span></h1>
                      <button type="button">Add To Bag</button> 
                      <div class="color-select">
                        <div class="select-item select-item-front">Front</div>
                      </div>
                    </div>
                  </div>

                  <div class="left-side"></div>
                  <div class="right-side"></div>
                </div>
              </div>
            </div>
            {% comment %} end flip orginal {% endcomment %}
        </div>
        {% endfor %}
      </div>




  </div>
</main>

{% endblock main %}

{% block js %}
<script src="{% static 'js/card.js' %}"></script>
{% endblock js %}

templates/pages/editor.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CK editor | Customized built</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <style>
      .helptext{display: none;}
    </style>

  </head>
  <body
    data-editor="DecoupledDocumentEditor"
    data-collaboration="false"
    data-revision-history="true"
  >
    {% include 'poster.html' %} 
    {% include 'navbar.html' %}
    <br />
    <main>

      <div class="form__container">
        <form action="" method="POST">

        </form>
      </div>

      <div class="centered">
        <div class="row">
          <div class="document-editor__toolbar"></div>
        </div>
        <div class="row row-editor">
          <div class="editor-container">
            <div class="editor">Start editting</div>
          </div>
        </div>
      </div>


      <section class="form-section">
        <form action="{% url 'main:add-expectation' %}" method="post"></form>
      </section>

    </main>

    <script src="{% static 'js/ckeditor.js' %}"></script>

    <script>
      DecoupledDocumentEditor.create(document.querySelector(".editor"), {
        licenseKey: "",
      })
        .then((editor) => {
          window.editor = editor;

          // Set a custom container for the toolbar.
          document
            .querySelector(".document-editor__toolbar")
            .appendChild(editor.ui.view.toolbar.element);
          document.querySelector(".ck-toolbar").classList.add("ck-reset_all");

        })
        .catch((error) => {
          console.error("Oops, something went wrong!");
          console.error(
            "Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:"
          );
          console.warn("Build id: hv6xm7adsxqm-atjvnpe2fn6r");
          console.error(error);
        });
    </script>
  </body>
</html>

templates/pages/kids.html
{% extends 'master.html' %} 
{% load static %} 

{% block head %}
<link rel="stylesheet" href="{% static 'css/teachers.css' %}" />
{% endblock head %} 


{% block title %}
শিশু বিনোদন - ক্যালিক্স স্কুল এন্ড কলেজ
{% endblock title %}

{% block poster %} 
{% include 'poster.html' %}
{% endblock poster %}

{% block main %}

<div class="teachers__title red-green-center ">
  <h1>
    <p>
      শিশু বিনোদন
    </p>
  </h1>
</div>

{% endblock main %}

templates/pages/lib.html
{% extends 'master.html' %} 
{% load static %} 

{% block head %}
<link rel="stylesheet" href="{% static 'css/lib.css' %}" />

<style>
  .lib__title h1 p{
    padding: .5rem 3.0rem;
  }
</style>

{% endblock head %} 


{% block title %}
পাঠাগার - ক্যালিক্স স্কুল এন্ড কলেজ
{% endblock title %}

{% block poster %} 
{% include 'poster.html' %}
{% endblock poster %}

{% block main %}
<main class="lib__main">




  {% for item in libs %}
  <div class="lib__title red-green-center">
  <h1>
    <p>
      {{item.short_name}}
      </p>
    </h1>
  </div>

      <h1 class="lib__title-promary" >{{item.title_of_post}}</h1>
      <div class="adviser__desc">

        {{item.description | safe}}
      </div>

        {% endfor %}
    </main>


{% endblock main %}

templates/pages/socialworks.html
{% extends 'master.html' %} 
{% load static %} 

{% block head %}

<link rel="stylesheet" href="{% static 'css/card.css' %}" />
{% endblock head %} 


{% block title %}
সামাজিক কর্মকাণ্ড - ক্যালিক্স স্কুল এন্ড কলেজ
{% endblock title %}

{% block poster %} 
{% include 'poster.html' %}
{% endblock poster %}

{% block main %}
<div class="socialworks__title red-green-center ">
  <h1>
    <p>
      সামাজিক কর্মকাণ্ড
    </p>
  </h1>
</div>



    

    <div class="container">
      <div class="product">
         <div class="product-inner" id="productBox">
          
          <div class="product-front">
            <div class="product-top">
              <h1>help</h1>
            </div>
            <div class="product-bottom">
              <p>Nike running shoes</p>
              <h2>Air Zoom Winflo 6</h2>
              <h1><span>$</span>120</h1>
              <button type="button">Add To Bag</button>
              <div class="color-select">
                <div class="select-item" onclick="flipRight()">Details</div>
              </div>
            </div>
          </div>
          
          <div class="product-back">
            <p>Test</p>
            <div class="product-top product-top2">
              <h1>Nike</h1>
            </div>
            <div class="product-bottom">
              <p>Students helping the poor</p>
              <h2>Air Zoom Winflo 6</h2>
              <h1><span>&nbsp;</span></h1>
              <button type="button">Add To Bag</button> 
              <div class="color-select">
                <div class="select-item" onclick="flipLeft()">01</div>
              </div>

             </div> 
          </div>

          <div class="left-side"></div>
          <div class="right-side"></div>
        </div>
      </div>
    </div>
    
{% endblock main %}

{% block js %}
<script src="{% static 'js/card.js' %}"></script>
{% endblock js %}

templates/pages/teacher.html
{% extends 'master.html' %} 
{% load static %} 

{% block head %}
<link rel="stylesheet" href="{% static 'css/teachers.css' %}" />
{% endblock head %} 


{% block title %}
শিক্ষকমণ্ডলী - ক্যালিক্স স্কুল এন্ড কলেজ
{% endblock title %}

{% block poster %} 
{% include 'poster.html' %}
{% endblock poster %}

{% block main %}

<div class="teachers__title red-green-center ">
  <h1>
    <p>
      {{teacher.nick_name}}
    </p>
  </h1>
</div>

<main class="teacher" >

  


</main>


{% endblock main %}

templates/pages/teachers.html
{% extends 'master.html' %} 
{% load static %} 

{% block head %}
<link rel="stylesheet" href="{% static 'css/teachers.css' %}" />
{% endblock head %} 


{% block title %}
শিক্ষকমণ্ডলী - ক্যালিক্স স্কুল এন্ড কলেজ
{% endblock title %}

{% block poster %} 
{% include 'poster.html' %}
{% endblock poster %}

{% block main %}

<div class="teachers__title red-green-center ">
  <h1>
    <p>
      শিক্ষকমণ্ডলী
    </p>
  </h1>
</div>

<main class="teachers-main" >
  <div class="teachers__grid">


{% for item in teachers %}

    
      <div class="teacher"  title="{{item.nick_name}}" data-href="{{item.pk}}" >

        <div class="teacher__top">
         <h1 class="teacher__title"> {{item.position}} </h1>
        </div>

        <div class="teacher__middle">
          <div class="teacher__name-box">
            <h2 class="teacher__name" >{{item.full_name}}</h2>
          </div>
          <div class="teacher__mobile-box">
            <p class="teacher__mobile">
              <a href="tel:{{item.phone}}"> মোবাইলঃ {{item.phone}} </a>
            </p>
          </div>
        </div>


        <div class="teacher__bottom">
          <div class="teacher__social">

            <ul class="social__links">
              <li class="social__link mail">
                <a href="tel:{{item.phone}}"> 
                  <svg width="50" height="50" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M41.6667 32.2917C39.0625 32.2917 36.5625 31.875 34.2292 31.1042C33.5 30.875 32.6875 31.0417 32.1042 31.6042L27.5208 36.1875C21.625 33.1875 16.7917 28.375 13.7917 22.4583L18.375 17.8542C18.9583 17.3125 19.125 16.5 18.8958 15.7708C18.125 13.4375 17.7083 10.9375 17.7083 8.33333C17.7083 7.1875 16.7708 6.25 15.625 6.25H8.33333C7.1875 6.25 6.25 7.1875 6.25 8.33333C6.25 27.8958 22.1042 43.75 41.6667 43.75C42.8125 43.75 43.75 42.8125 43.75 41.6667V34.375C43.75 33.2292 42.8125 32.2917 41.6667 32.2917ZM39.5833 25H43.75C43.75 14.6458 35.3542 6.25 25 6.25V10.4167C33.0625 10.4167 39.5833 16.9375 39.5833 25ZM31.25 25H35.4167C35.4167 19.25 30.75 14.5833 25 14.5833V18.75C28.4583 18.75 31.25 21.5417 31.25 25Z" fill="#000000"/>
                  </svg>
                </a>
              </li>
              <li class="social__link">
                <a href="mailto:{{item.email}}"> 
                  <svg xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 48 48" width="4.8rem" height="4.8rem"><path fill="#e0e0e0" d="M5.5,40.5h37c1.933,0,3.5-1.567,3.5-3.5V11c0-1.933-1.567-3.5-3.5-3.5h-37C3.567,7.5,2,9.067,2,11v26C2,38.933,3.567,40.5,5.5,40.5z"/><path fill="#d9d9d9" d="M26,40.5h16.5c1.933,0,3.5-1.567,3.5-3.5V11c0-1.933-1.567-3.5-3.5-3.5h-37C3.567,7.5,2,9.067,2,11L26,40.5z"/><path fill="#eee" d="M6.745,40.5H42.5c1.933,0,3.5-1.567,3.5-3.5V11.5L6.745,40.5z"/><path fill="#e0e0e0" d="M25.745,40.5H42.5c1.933,0,3.5-1.567,3.5-3.5V11.5L18.771,31.616L25.745,40.5z"/><path fill="#ca3737" d="M42.5,9.5h-37C3.567,9.5,2,9.067,2,11v26c0,1.933,1.567,3.5,3.5,3.5H7V12h34v28.5h1.5c1.933,0,3.5-1.567,3.5-3.5V11C46,9.067,44.433,9.5,42.5,9.5z"/><path fill="#f5f5f5" d="M42.5,7.5H24H5.5C3.567,7.5,2,9.036,2,11c0,1.206,1.518,2.258,1.518,2.258L24,27.756l20.482-14.497c0,0,1.518-1.053,1.518-2.258C46,9.036,44.433,7.5,42.5,7.5z"/><path fill="#e84f4b" d="M43.246,7.582L24,21L4.754,7.582C3.18,7.919,2,9.297,2,11c0,1.206,1.518,2.258,1.518,2.258L24,27.756l20.482-14.497c0,0,1.518-1.053,1.518-2.258C46,9.297,44.82,7.919,43.246,7.582z"/></svg>
                </a>
              </li>
              <li class="social__link">
                <a href="{{item.facebook}}" target="_blank"> 
                  

                  <svg xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 48 48" width="4.8rem" height="4.8rem"><path fill="#039be5" d="M24 5A19 19 0 1 0 24 43A19 19 0 1 0 24 5Z"/><path fill="#fff" d="M26.572,29.036h4.917l0.772-4.995h-5.69v-2.73c0-2.075,0.678-3.915,2.619-3.915h3.119v-4.359c-0.548-0.074-1.707-0.236-3.897-0.236c-4.573,0-7.254,2.415-7.254,7.917v3.323h-4.701v4.995h4.701v13.729C22.089,42.905,23.032,43,24,43c0.875,0,1.729-0.08,2.572-0.194V29.036z"/></svg>
                </a>
              </li>
              <li class="social__link">
                <a href="{{item.twitter}}" target="_blank">
                  <svg  xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 48 48" width="5.0rem" height="5.0rem"><path fill="#03a9f4" id="tw" d="M42,12.429c-1.323,0.586-2.746,0.977-4.247,1.162c1.526-0.906,2.7-2.351,3.251-4.058c-1.428,0.837-3.01,1.452-4.693,1.776C34.967,9.884,33.05,9,30.926,9c-4.08,0-7.387,3.278-7.387,7.32c0,0.572,0.067,1.129,0.193,1.67c-6.138-0.308-11.582-3.226-15.224-7.654c-0.64,1.082-1,2.349-1,3.686c0,2.541,1.301,4.778,3.285,6.096c-1.211-0.037-2.351-0.374-3.349-0.914c0,0.022,0,0.055,0,0.086c0,3.551,2.547,6.508,5.923,7.181c-0.617,0.169-1.269,0.263-1.941,0.263c-0.477,0-0.942-0.054-1.392-0.135c0.94,2.902,3.667,5.023,6.898,5.086c-2.528,1.96-5.712,3.134-9.174,3.134c-0.598,0-1.183-0.034-1.761-0.104C9.268,36.786,13.152,38,17.321,38c13.585,0,21.017-11.156,21.017-20.834c0-0.317-0.01-0.633-0.025-0.945C39.763,15.197,41.013,13.905,42,12.429"/></svg>
                </a>
              </li>
            </ul>
          </div>
          {% comment %} teacher social{% endcomment %}
        </div>
      </div>



{% endfor %}

  </div>
</main>
   


{% endblock main %}


{% block js %}
<script>

const card = document.getElementsByClassName("teacher");

for (let i = 0; i < card.length; i++) {
  const e = card[i];

  console.log(e);

  e.style.cursor = "pointer";
  e.addEventListener("click", (_) => {
    window.location.assign(e.dataset.href);
  });
}

</script>
{% endblock js %}