calix/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('main.urls')),
    path('', include('right.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# 01732168213

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home-main'),

    path('advisers/', views.advisers, name='advisers'),
    path('advisers/<int:id>', views.adviser, name='adviser'),

    path('directors/', views.directors, name='directors'),
    path('directors/<int:id>', views.director, name="director"),

    path('committee/', views.committee, name='committee'),

    path('teachers/', views.teachers, name='teachers'),
    path('teachers/<int:id>', views.teacher, name='teacher'),

    path('lib/', views.lib, name='lib'),
    path('annualreport/', views.annualreport, name='annualreport'),

    path('expectation/', views.expectation, name='expectation'),
    path('expectation/add', views.add_expectation, name='add-expectation'),



    path('socialworks/', views.socialworks, name='socialworks'),

    path('about_us/', views.about_us, name='about_us'),
    path('started/', views.started, name='started'),
    path('kids/', views.kids, name='kids'),
    path('contact/', views.contact, name='contact'),
]

right/urls.py
from django.urls import path
from .views import *


app_name = "right"
urlpatterns = [
    path('notice/', notice, name="notice"),
    path('results/', results, name="results"),
    path('admission/', admission, name="admission"),
    path('others/', others, name="others"),

    path('gallery/', gallery, name="gallery"),

    # student-corner
    path('quran/', quran, name="quran"),
    path('islamic/', islamic, name="islamic"),
    path('book_list/', book_list, name="book_list"),
    path('gk/', gk, name="gk"),
    path('by_student/', by_student, name="by_student"),
    path('nutrition/', nutrition, name="nutrition"),
    path('about_student/', about_student, name="about_student"),
    path('general_education/', general_education, name="general_education"),
    path('technical_education/', technical_education, name="technical_education"),
    path('adult_education/', adult_education, name="adult_education"),

]

templates/footer.html
{% load static %}

<footer class="footer footer-main" id="footer">
  <div class="footer__top">
    <h3 class="footer__title">
      <img
        class="footer__logo"
        src="{% static 'img/logo.svg' %}"
        alt="Our logo"
      />
    </h3>
  </div>
  <div class="footer__bottom">
    <!-- <div class="footer__bottom-left">
        <ul class="footer__links">
          <li class="footer__link"><a href="/">HOME</a></li>
          <li class="footer__link"><a href="#">Notice</a></li>
          <li class="footer__link"><a href="#">Results</a></li>
          <li class="footer__link"><a href="#">Tearms and conditions</a></li>
          <li class="footer__link"><a href="#">IT Support</a></li>
        </ul>
      </div>
      <div class="footer__bottom-right">

      </div> -->

    <h6 class="copyright">
      &copy; সর্বস্বত্ব সংরক্ষিত <br />
      <span class="habibullah"> কোড লিখেছেন মোহাম্মদ হাবিবুল্লাহ</span>
      <span class="forid">
        <br />
        ডিজাইন পরিকল্পনা মোঃ শেখ ফরিদ</span
      >
    </h6>
  </div>
</footer>

templates/index.html
{% extends "master.html" %} 
{% load static %} 

{% block poster %} 
{% include 'poster.html' %} 
{% endblock poster %}

{% block title %} 
Home || Calix schools and college 
{% endblock title %} 

{% block main %}

<main class="main-content">
  <div class="main-left">
    <ul class="main-left__links">
      <li class="main-left__link">
        <a href="{% url 'main:advisers' %}">উপদেষ্টামণ্ডলী</a>
      </li>
      <li class="main-left__link">
        <a href="{% url 'main:directors' %}">পরিচালকবৃন্দ</a>
      </li>
      <li class="main-left__link">
        <a href="{% url 'main:committee' %}">কমিটির সদস্যবৃন্দ</a>
      </li>
      <li class="main-left__link">
        <a href="{% url 'main:teachers' %}">শিক্ষকমণ্ডলী</a>
      </li>
      <li class="main-left__link">
        <a href="{% url 'main:lib' %}">পাঠাগার</a>
      </li>
      <li class="main-left__link">
        <a href="{% url 'main:annualreport' %}">বার্ষিক প্রতিবেদন</a>
      </li>
      <li class="main-left__link">
        <a href="{% url 'main:expectation' %}">প্রত্যাশা</a>
      </li>
      <li class="main-left__link">
        <a href="{% url 'main:socialworks' %}">সামাজিক কর্মকাণ্ড</a>
      </li>
    </ul>
  </div>

  <div class="main__middle">
    <div class="pages">
      <ul class="page__links">
        <li class="page__link">
          <a href="{% url "right:notice" %}">নোটিশ বোার্ড/বিজ্ঞপ্তি</a>
        </li>
        <li class="page__link">
          <a href="{% url "right:results" %}">ফলাফল</a>
        </li>
        <li class="page__link">
          <a href="{% url "right:admission" %}">ভর্তি ফরম</a>
        </li>
        <li class="page__link">
          <a href="{% url "right:others" %}">অন্যান্য</a>
        </li>
      </ul>

      <div class="notice">
        <h3 class="notice__title">
          {{notice.title}}
        </h3>
        <p class="notice__description">
          {{notice.description | safe}}
        </p>
      </div>

    </div>

    <!-- image display -->
    <div class="img-display">
      <div class="img-display__title">
        <!-- need to work here -->
        <p>
          <a
            class="img-display__title--link"
            href="{% url 'right:gallery' %}"
            >ছবি সমাহার</a
          >
        </p>
      </div>

      <div class="calix-school-college">
        <!-- <h3 class="sc-title">ক্যালিক্স স্কুল এণ্ড কলেজ</h3>
          <div class="img__container">

            <div class="images">

              <div class="g1-img__box">
                <img class="g-img chairman" src="{% static 'img/chairman.jpg' %}" alt="The chairman">
              </div>

            </div>
          </div> -->
      </div>

      <!-- slide show started here -->

      <div class="slideshow-container">
        <div class="mySlides fade">
          <div class="numbertext">1 / 5</div>
          <img src="{% static 'img/chairman.jpg' %}" style="width: 100%" />
          <div class="text">The chairman of institute.</div>
        </div>

        <div class="mySlides fade">
          <div class="numbertext">2 / 5</div>
          <img
            src="{% static 'img/teacher_speech.jpg' %}"
            style="width: 100%"
          />
          <div class="text">Teacher talking</div>
        </div>

        <div class="mySlides fade">
          <div class="numbertext">3 / 5</div>
          <img
            src="{% static 'img/student_talking.jpg' %}"
            style="width: 100%"
          />
          <div class="text">Student talking</div>
        </div>

        <div class="mySlides fade">
          <div class="numbertext">4 / 5</div>
          <img src="{% static 'img/school_16x9.jpg' %}" style="width: 100%" />
          <div class="text">Students</div>
        </div>

        <div class="mySlides fade">
          <div class="numbertext">5 / 5</div>
          <img src="{% static 'img/school_bus.jpg' %}" style="width: 100%" />
          <div class="text">School Bus</div>
        </div>

        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
        <a class="next" onclick="plusSlides(1)">&#10095;</a>
      </div>
      <br />

      <div style="text-align: center">
        <span class="dot" onclick="currentSlide(1)"></span>
        <span class="dot" onclick="currentSlide(2)"></span>
        <span class="dot" onclick="currentSlide(3)"></span>
        <span class="dot" onclick="currentSlide(4)"></span>
        <span class="dot" onclick="currentSlide(5)"></span>
      </div>

      <!-- slide show started -->
    </div>
    <!-- end of image display -->
  </div>

  <div class="main__right">
    <!-- the login form for all -->
    <form action="#" class="login__form">
      <label class="uid__lable" for="uid">
        <input
          class="uid"
          type="text"
          name="uid"
          required
          id="uid"
          placeholder="ব্যবহারকারীর নাম"
        />
        <br />
      </label>
      <label for="password" class="password__lable">
        <input
          class="password"
          type="password"
          min="6"
          required
          name="password"
          id="password"
          placeholder="গোপন নাম্বার"
        />
        <br />
      </label>

      <button class="login__btn" type="submit">প্রবেশ</button>
    </form>

    <!-- end of the login form for all -->

    <!-- student corner -->
    <div class="student-corner">
      <ul class="student-corner__links">
        <li class="student-corner__link">
          <a href="{% url 'right:quran' %}">পবিত্র আল-কুরআন</a>
        </li>
        <li class="student-corner__link"><a href="{% url 'right:islamic' %}">ইসলামিক আলোচনা</a></li>
        <li class="student-corner__link">
          <a href="{% url 'right:book_list' %}">প্রতিযোগিতা সমূহ</a>
        </li>
        <li class="student-corner__link">
          <a href="{% url 'right:gk' %}">সাধারণ জ্ঞানের আসর</a>
        </li>
        <li class="student-corner__link">
          <a href="{% url 'right:by_student' %}">শিক্ষার্থী কর্তৃক রচিত</a>
        </li>
        <li class="student-corner__link"><a href="{% url 'right:nutrition' %}">পুষ্টি কর্ণার</a></li>
        <li class="student-corner__link">
          <a href="{% url 'right:about_student' %}">শিক্ষার্থীর তথ্যসমূহ</a>
        </li>
        <li class="student-corner__link">
          <a href="{% url 'right:book_list' %}">শিক্ষার্থীর প্রয়োজনে</a>
        </li>
      </ul>
    </div>
    <!-- end of student corner -->

    <!-- official info -->
    <div class="our-info">
      <!-- title -->
      <h2 class="our-info__title">শিক্ষা কার্যক্রম</h2>
      <!-- links -->
      <ul class="our-info__links">
        <li class="our-info__link">
          <span class="hand-icon">&#9758;</span><a href="{% url 'right:general_education' %}"> সাধারণ শিক্ষা</a>
        </li>
        <li class="our-info__link">
          <span class="hand-icon">&#9758;</span><a href="{% url 'right:technical_education' %}"> কারিগরি শিক্ষা</a>
        </li>
        <li class="our-info__link">
          <span class="hand-icon">&#9758;</span><a href="{% url 'right:adult_education' %}"> বয়স্ক শিক্ষা</a>
        </li>
      </ul>
    </div>
    <!-- end of official info -->
  </div>
</main>

{% endblock main %} 

{% block js %}
<script>
  var slideIndex = 1;
  showSlides(slideIndex);

  function plusSlides(n) {
    showSlides((slideIndex += n));
  }

  function currentSlide(n) {
    showSlides((slideIndex = n));
  }

  function showSlides(n) {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("dot");
    if (n > slides.length) {
      slideIndex = 1;
    }
    if (n < 1) {
      slideIndex = slides.length;
    }
    for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
    }
    for (i = 0; i < dots.length; i++) {
      dots[i].classList.remove("active");
    }
    slides[slideIndex - 1].style.display = "block";
    dots[slideIndex - 1].classList.add("active");
  }

</script>
{% endblock js %}

templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr" >
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>{% block title %}Calix school{% endblock title %}</title>
    <link rel="stylesheet" href=" {% static 'css/style.css' %} " />
    {% block head %}
    
    {% endblock head %}
    
    <link rel="stylesheet" href=" {% static 'css/mobile-nav.css' %} " />
    <link rel="stylesheet" href=" {% static 'css/responsive.css' %} " />

    
  </head>

  <body>
    
   

{% block poster %}
{% endblock poster %}

{% include 'navbar.html' %}
{% include 'mobile-nav.html' %}


{% block main %} 
{% endblock main %} 

{% include 'footer.html' %}

{% block js %}
{% endblock js %}

    <script defer src=" {% static 'js/main.js' %}"></script>
  </body>
</html>

templates/mobile-nav.html
<div class="navigation">
   <input type="checkbox" class="navigation__checkbox" id="navi-toggle">
   <label for="navi-toggle" class="navigation__button">
   <span class="navigation__icon">&nbsp;</span>
   </label>
   <div class="navigation__background">&nbsp;</div>
   <nav class="navigation__nav">
      <ul class="navigation__list">
         <li class="navigation__item"><a href="/" class="navigation__link"><span>০১</span>মূল পাতা</a></li>
         <li class="navigation__item"><a href="{% url 'main:about_us' %}" class="navigation__link"><span>০২</span>প্রতিষ্ঠানের তথ্য</a></li>
         <li class="navigation__item"><a href="{% url 'main:started' %}" class="navigation__link"><span>০৩</span>শুভ উদ্ধোধন</a></li>
         <li class="navigation__item"><a href="{% url 'main:kids' %}" class="navigation__link"><span>০৪</span>শিশু বিনোদন</a></li>

         <li class="navigation__item"><a href="{% url 'main:contact' %}" class="navigation__link"><span>০৫</span>যোগাযোগ</a></li>
         <li class="navigation__item"><a href="/admin" class="navigation__link"><span>০৬</span>এডমিন প্রবেশ</a></li>
      </ul>
   </nav>
</div>

templates/navbar.html
{% load static %}
<nav id="nav-bar" class="nav-bar">

  <ul class="nav__links">
    <li class="nav__link nav__link--main-page">
      <a id="main-page" href="/">মূল পাতা </a>
    </li>

    <div class="nav__links--right">
      <li class="nav__link">
        <a href="{% url 'main:about_us' %}"> প্রতিষ্ঠানের তথ্য</a>
      </li>
      <li class="nav__link">
        <a href="{% url 'main:started' %}">শুভ উদ্ধোধন</a>
      </li>
      <li class="nav__link">
        <a href="{% url 'main:kids' %}">শিশু বিনোদন</a>
      </li>
      <li class="nav__link">
        <a href="{% url 'main:contact' %}"> যোগাযোগ</a>
      </li>
      <li class="nav__link">
        <a href="/admin">এডমিন প্রবেশ</a>
      </li>
    </div>
  </ul>
</nav>

templates/poster.html
{% load static %}

<header>
  <div class="logo__box">
    <span class="established-year">২০১৮ খ্রিষ্টাব্দ থেকে-</span>
    <img class="logo__img" src="{% static 'img/logo.svg' %}" alt="main" />
    <p class="our-slogan">শুধু ভাল ছাত্র নয়, ভাল মানুষও চাই</p>
  </div>

  <div class="header__info">
    <h1 class="main__head">ক্যালিক্স স্কুল এণ্ড কলেজ</h1>
    <h2 class="sub-heading">ভাটরা, খানপুর, শেরপুর, বগুড়া</h2>
    <h3 class="mobile-number">
      <p>
        <a title="কল করতে ক্লিক করুন" href="tel:+8801716284672">
          <span>মোবাইলঃ &#9990;</span> ০১৭১৬২৮৪৬৭২</a
        >
        <br />
        <a href="mailto:calix.school.college@gmail.com"
          ><span>ই-মেইল &#9993; </span> calix.school.college@gmail.com</a
        >
      </p>
    </h3>
  </div>
</header>